### ISSUE TITLE
ModuleNotFoundError: No module named 'hamster'

### ISSUE THREAD

**Issue by marcbria** [GeraldJansen/hamster-tool#2]
When running the tool as this in a brand new ubuntu 19.10 over master branch:
`$ ./htool --db-dir ~/snap/hamster-snap/current/.local/share/hamster/hamster.db export tsv 2018-01-01 $(date +%y-%m-%d) 
`
O got this error:

```
Traceback (most recent call last):
  File "./htool", line 38, in <module>
    from hamster import reports
ModuleNotFoundError: No module named 'hamster'
```

**Comment by GeraldJansen** [comment]
Thanks for the feedback. This tool is expecting hamster to be installed in the standard python3 module path. I have only tested it with hamster manually installed system-wide, not using snap.

**Comment by marcbria** [comment]
Ok. Thanks.
