### ISSUE TITLE
TypeError: 'Fact' object is not subscriptable when using htool with GitHub version of hamster.

### ISSUE THREAD

**Issue by taniwallach** [GeraldJansen/hamster-tool#3]
I tried to use `htool` to export data, after installing hamster from https://github.com/projecthamster/hamster.git.
The current master branch was at ceedcd87d7591301dcd7648c7f28a37604362486.

I get the following error.
```
tani@lxtani:~/hamster-tool$ ./htool export tsv 2020-01-01 
Traceback (most recent call last):
  File "./htool", line 261, in <module>
    getattr(hamster_tool, args.action)(*args.action_args)
  File "./htool", line 101, in export
    for f in self.db_storage.get_facts(start_date, end_date, '')]
  File "./htool", line 101, in <listcomp>
    for f in self.db_storage.get_facts(start_date, end_date, '')]
 TypeError: 'Fact' object is not subscriptable
```
The database is being read, as if I add:
```
         all_facts = self.db_storage.get_facts(start_date, end_date, '')
         list_all_facts = list( all_facts )
         for pi in list_all_facts:
             print(pi)
```
just above the `facts = ` line in the export code, a printout of records is given.

It seems that replacing the definition of `facts` in the export routine by
```
        facts = self.db_storage.get_facts(start_date, end_date, '')
```
allow the code to create the expected output in both output formats.

Apparently some changes to hamster v 3 has interfered with what you code is doing.

**Comment by GeraldJansen** [comment]
Thanks for your report and the suggested fix! Your fix works nicely for "export".  However, there is something else broken now for the "load" function. I hope to be able to fix it fairly quickly...

**Comment by GeraldJansen** [comment]
Master should work now. (Note two extra commits after this merge - sorry for the mess).
